version: '3'
services:
  web:
    build:
      context: .
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: radio_system_dev
      PG_PORT: 5432

      PG_HOST: db
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - pgdata:/usr/local/var/postgres
volumes:
  pgdata:
